### ISSUE TITLE
Login HTML page

### ISSUE THREAD

**Issue by alexbcastana** [cpe308-309/winter-spring2017-AL#19] opened 2017-04-09 15:44 UTC
The goal is to create a simple login front-end page. It will contain the name of the project, an email input text box, a password input text box, and a sign in button.

**Comment by alexbcastana** [comment] 2017-04-09 15:48
As of 4/9/2017, a login page has been created with an email input, password input, and a sign in input button. The next step is to add the CSS to the form to organize and customize the login page.

**Comment by leklein** [comment] 2017-04-10 00:11
Is #14 a duplicate of this issue?  And if so, can I close it (14)?

**Comment by alexbcastana** [comment] 2017-04-14 00:41
You can close it.
Currently I have pushed the login page to master and it is connected to the single page routing architecture.

**Closed** 2017-04-17 17:16 UTC
Labels: in progress, product backlog
